services:
  wartungsplan:
    build: .
    container_name: wartungsplan
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./Journal:/app/Journal
      - ./Journal_Archiv:/app/Journal_Archiv
      - ./data/database.sqlite:/app/database.sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wartungsplan.rule=Host(`wartungsplan.jennidesign.eu`)"
      - "traefik.http.routers.wartungsplan.entrypoints=websecure"
      - "traefik.http.routers.wartungsplan.tls=true"
      - "traefik.http.routers.wartungsplan.tls.certresolver=letsencrypt"
      - "traefik.http.services.wartungsplan.loadbalancer.server.port=3000"
